parameters:
  tools:
    # This is the order they will appear in the interface.
    - AdminScore
    - AdminStats
    - ArticleInfo
    - Authorship
    - AutoEdits
    - Blame
    - CategoryEdits
    - EditCounter
    - EditSummary
    - GlobalContribs
    - LargestPages
    - Pages
    - Quote
    - RfX
    - RfXVote
    - SimpleEditCounter
    - TopEdits
